### ISSUE TITLE
[Feature] 프로젝트 셋업

### ISSUE THREAD

**Issue by BGMSound** [kakao-tech-campus-2nd-step3/Team22_BE#1]
## 어떤 기능인가요?
> 프로젝트 전반에 필요한 코어와 유틸, 그리고 advice 를 추가합니다.

## To-Do
+ core
  + exception
    + [x] ErrorCode 정의 & 애플리케이션 exception 상속을 위한 APIException 구현
    + [x] Common Exception & Common ErrorCode 구현
  + identification
    + [x] IdentifierGenerator 정의
  + persistence
    + [x] Persistence Operation 을 위한 Functional Interface & Gateway 정의
    + [x] persistence entity 가 상속할 base entity 구현 & 사용자 데이터 join 을 위한 user entity 구현
  + user
    + [x] 사용자 데이터와 역할, Repository 정의 
 + advice
   + [x] APIExceptionHandler 구현
   + [x] core 모듈에서 정의한 공통 컴포넌트 구현
## 관련 이슈
>

## 참고 자료
>
