### ISSUE TITLE
[Feature] 음악 공유 기능

### ISSUE THREAD

**Issue by GyuminBae** [kakao-tech-campus-2nd-step3/Team22_BE#21]
## 어떤 기능인가요?
> 친구들에게 음악을 공유할 수 있습니다. 

## To-Do
- [x] 음악 조회 시 DB에 존재하지 않는 음악이면 insert
- [x] 음악을 친구들에게 공유하기
- [x] 공유한 음악 조회하기
- [x] 공유 받은 음악 조회하기
