### ISSUE TITLE
[Feature] 마이페이지 기능 구현

### ISSUE THREAD

**Issue by Youngini** [kakao-tech-campus-2nd-step3/Team22_BE#8]
## 어떤 기능인가요?
> 사용자의 마이페이지에서 사용할 기능들 입니다. 
사용자 정보를 불러오고 사용자 정보를 수정하는 기능을 구현하려고 합니다.

## To-Do
- [ ] 사용자 정보 조회
- [ ] 사용자 정보 수정
- [ ] 선호하는 음악 장르 선택
- [ ] 사용자 프로필 이미지 수정
- [ ] 탈퇴 기능

## 관련 이슈
> 특정 이슈에 대한 후속 조치일 경우 해당 이슈를 언급해주세요! ex) #이슈번호

## 참고 자료
> 도움이 되거나 참고할 자료가 있으면 적어주세요!
